name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags: ["*"]
env:
  DOCKER_REGISTRY_SERVER: "https://registry.cn-shanghai.aliyuncs.com"
  DOCKER_REGISTRY_HOST: "registry.cn-shanghai.aliyuncs.com"
  IMAGE_NAME: "wei-z/azcli-container"
  
jobs:

  Daily-build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $DOCKER_REGISTRY_HOST/$IMAGE_NAME:latest
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: "${{ env.DOCKER_REGISTRY_HOST }}"
        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWORD }}"
        
    - name: Push image
      run: |
        docker push $DOCKER_REGISTRY_HOST/$IMAGE_NAME:latest
        
  Release-build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $DOCKER_REGISTRY_HOST/$IMAGE_NAME:${{ github.ref_name }}
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server:  "${{ env.DOCKER_REGISTRY_HOST }}"
        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWORD }}"
        
    - name: Push image
      run: |
        docker push $DOCKER_REGISTRY_HOST/$IMAGE_NAME:${{ github.ref_name }}
